require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - db/**/*
    - vendor/**/*
    - log/**/*
    - bin/*
    - lib/scripts/temporary/**/*
    - config/routes/**/*
    - config/application.rb
    - config/initializers/*
    - config/environments/*
    - node_modules/**/*
    - tmp/**/*
    - storage/**/*
    - 'lib/tasks/**/*'
    - 'app/controllers/e2e_support_controller.rb'
    - config/boot.rb
    - config/environment.rb

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 100
  Exclude:
    - 'Gemfile'

Lint/EmptyBlock:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Metrics/BlockLength:
  IgnoredMethods:
    - 'config'
    - 'configure'
    - 'context'
    - 'describe'
    - 'included'
    - 'it'
    - 'setup'
    - 'shared_context'
    - 'shared_examples_for'
    - 'register'
  Exclude:
    - 'spec/factories/**/*'
    - 'config/routes.rb'
    - 'spec/requests/swagger/**/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']

Naming/RescuedExceptionsVariableName:
  PreferredName: 'exception'

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true
  EnforcedStyle: braces

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/MutableConstant:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantAssignment:
    Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false
