version: "3"

services:
  postgres:
    image: "postgres:12"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  web:
    depends_on:
      - "postgres"
      - "mailcatcher"
    build: .
    command: bash -c "(bundle check || bundle install) && bundle exec puma -C config/puma.rb"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/studio-api
      - gems:/gems

  mailcatcher:
    image: zolweb/docker-mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres:
  gems:
