---
swagger: '2.0'
info:
  title: Studio api
  version: v1
paths:
  "/api/exercises":
    post:
      summary: create exercise
      tags:
      - Exercise
      consumes:
      - application/json
      parameters:
      - name: exercise
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            muscular_group_id:
              type: string
          required:
          - name
          - muscular_group_id
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '201':
          description: successful
    get:
      summary: List exercises
      tags:
      - Exercise
      consumes:
      - application/json
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
  "/api/exercises/{id}":
    get:
      summary: Show exercise
      tags:
      - Exercise
      consumes:
      - application/json
      parameters:
      - in: path
        type: string
        name: id
        required: true
        description: ID
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
    put:
      summary: Update exercise
      tags:
      - Exercise
      consumes:
      - application/json
      parameters:
      - name: exercise
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            muscular_group_id:
              type: string
          required:
          - name
          - muscular_group_id
      - in: path
        type: string
        name: id
        required: true
        description: ID
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
  "/api/exercise_workout_plans":
    post:
      summary: create exercise_workout_plan
      tags:
      - Exercise Workout Plan
      consumes:
      - application/json
      parameters:
      - name: exercise_workout_plan
        in: body
        schema:
          type: object
          properties:
            workout_plan_id:
              type: string
            exercise_id:
              type: string
            repetitions:
              type: string
            rest:
              type: string
            exercise_sequence:
              type: integer
          required:
          - workout_plan_id
          - exercise_id
          - repetitions
          - rest
          - exercise_sequence
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '201':
          description: successful
    get:
      summary: List exercise_workout_plans
      tags:
      - Exercise Workout Plan
      consumes:
      - application/json
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
  "/api/exercise_workout_plans/{id}":
    get:
      summary: Show exercise workout plan
      tags:
      - Exercise Workout Plan
      consumes:
      - application/json
      parameters:
      - in: path
        type: string
        name: id
        required: true
        description: ID
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
    put:
      summary: Update exercise_workout_plan
      tags:
      - Exercise Workout Plan
      consumes:
      - application/json
      parameters:
      - name: exercise_workout_plan
        in: body
        schema:
          type: object
          properties:
            workout_plan_id:
              type: string
            exercise_id:
              type: string
            repetitions:
              type: string
            rest:
              type: string
            exercise_sequence:
              type: integer
          required:
          - workout_plan_id
          - exercise_id
          - repetitions
          - rest
          - exercise_sequence
      - in: path
        type: string
        name: id
        required: true
        description: ID
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
  "/api/users/login":
    post:
      summary: authenticate user
      tags:
      - Authentication
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              format: email
            password:
              type: string
              format: password
          required:
          - email
          - password
      responses:
        '200':
          description: successful
  "/api/workout_plans":
    post:
      summary: create workout plan
      tags:
      - Workout Plan
      consumes:
      - application/json
      parameters:
      - name: workout_plan
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '201':
          description: successful
    get:
      summary: List workout_plans
      tags:
      - Workout Plan
      consumes:
      - application/json
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
  "/api/workout_plans/{id}":
    get:
      summary: Show workout_plan
      tags:
      - Workout Plan
      consumes:
      - application/json
      parameters:
      - in: path
        type: string
        name: id
        required: true
        description: ID
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
    put:
      summary: Update workout plan
      tags:
      - Workout Plan
      consumes:
      - application/json
      parameters:
      - name: workout_plan
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      - in: path
        type: string
        name: id
        required: true
        description: ID
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
servers:
- url: https://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
