---
swagger: '2.0'
info:
  title: Studio api
  version: v1
paths:
  "/api/users/login":
    post:
      summary: authenticate user
      tags:
      - Authentication
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              format: email
            password:
              type: string
              format: password
          required:
          - email
          - password
      responses:
        '200':
          description: successful
servers:
- url: https://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
