---
swagger: '2.0'
info:
  title: Studio api
  version: v1
paths:
  "/api/exercises":
    post:
      summary: create exercise
      tags:
      - Exercise
      consumes:
      - application/json
      parameters:
      - name: exercise
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            muscular_group_id:
              type: string
          required:
          - name
          - muscular_group_id
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '201':
          description: successful
  "/api/exercises/{id}":
    get:
      summary: Show exercise
      tags:
      - Exercise
      consumes:
      - application/json
      parameters:
      - in: path
        type: string
        name: id
        required: true
        description: ID
      - in: header
        type: string
        name: Authorization
        required: true
        description: Auth token
      security:
      - Bearer: {}
      responses:
        '200':
          description: successful
  "/api/users/login":
    post:
      summary: authenticate user
      tags:
      - Authentication
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              format: email
            password:
              type: string
              format: password
          required:
          - email
          - password
      responses:
        '200':
          description: successful
servers:
- url: https://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
