default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  port: 5432
  host: <%= ENV['DEV_DATABASE_HOST'] %>

development:
  <<: *default
  database: studio_api_development

test:
  <<: *default
  database: studio_api_test
  user: postgres
  password: passwd
  host: <%= ENV['TEST_DATABASE_HOST'] %>
